
/*
 * FrameWebcam.java
 * Created on 2009-09-02, 18:27:52
 */
package sensetile.components;

import java.awt.Graphics;

import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import sensetile.common.components.SenseTileView;
import sensetile.common.sources.ISource;
import sensetile.common.utils.Guard;
import sensetile.video.controls.VideoGrabber;
import sensetile.video.exporter.VideoExporterAVI;
import sensetile.video.sources.IVideoSource;
/**
 *
 * @author SenseTile
 */
public class FrameViewer extends JInternalFrame {

    IVideoSource _source = null;
    private int _width = ISource.DEFAULT_WIDTH;
    private int _height = ISource.DEFAULT_HEIGHT;
    private int _parentWidth = 640;
    private int _parentHeight =480;
    private  VideoExporterAVI avi= null;
   
    /** Creates new form FrameWebcam */
    public FrameViewer()
    {
        initComponents();
       
    }
    public void setParentSize(int width,int height){
        _parentWidth=width;
        _parentHeight=height;
    }

    public void setOutputSize(int width, int height) {
        _width = width;
        _height = height;
    }

    public void setSource(final IVideoSource source)
    {
        Guard.ArgumentNotNull(source, "Source cannot be a null.");
        _source = source;

    }

    public void setGrabberToPanViewer(final VideoGrabber grabber)
    {
        Guard.ArgumentNotNull(grabber, "VideoGrabber cannot be a null.");
        panViewer.add(grabber, BorderLayout.CENTER);
    }
  
    public void startSource(boolean autoStart)
    {
        FrameViewerControler.getInstance().startSource(_source, autoStart);
    }

    public IVideoSource getSource() {
        return _source;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpCaptureSize = new javax.swing.ButtonGroup();
        panViewer = new javax.swing.JPanel();
        panelStatus = new java.awt.Panel();
        lblActualFileSize = new javax.swing.JLabel();
        lblActualRecordingTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOutput = new javax.swing.JMenu();
        mnuMovieViewer = new javax.swing.JMenu();
        mnuItemStart = new javax.swing.JMenuItem();
        mnuItemStop = new javax.swing.JMenuItem();
        mnuBroadcast = new javax.swing.JMenu();
        mnuBroadcastStart = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sensetile/Languages"); // NOI18N
        setTitle(bundle.getString("IMAGE")); // NOI18N
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sensetile/resources/tango/image-x-generic.png"))); // NOI18N
        setOpaque(false);
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        panViewer.setBackground(java.awt.Color.red);
        panViewer.setDoubleBuffered(false);
        panViewer.setName("panViewer"); // NOI18N
        panViewer.setOpaque(false);
        panViewer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panViewerMousePressed(evt);
            }
        });
        panViewer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panViewer, java.awt.BorderLayout.CENTER);

        panelStatus.setName("paneStatus"); // NOI18N

        lblActualFileSize.setForeground(new java.awt.Color(236, 11, 11));
        lblActualFileSize.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblActualFileSize.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblActualFileSize.setName("lblActualFileSize"); // NOI18N
        lblActualFileSize.setPreferredSize(new java.awt.Dimension(200, 19));

        lblActualRecordingTime.setForeground(new java.awt.Color(236, 11, 11));
        lblActualRecordingTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblActualRecordingTime.setName("lblActualRecordingTime"); // NOI18N
        lblActualRecordingTime.setPreferredSize(new java.awt.Dimension(100, 17));

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblActualFileSize, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblActualRecordingTime, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblActualFileSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblActualRecordingTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
        );

        getContentPane().add(panelStatus, java.awt.BorderLayout.PAGE_END);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        mnuOutput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sensetile/resources/tango/transmit_blue.png"))); // NOI18N
        mnuOutput.setText(bundle.getString("OUTPUT")); // NOI18N
        mnuOutput.setName("mnuOutput"); // NOI18N

        mnuMovieViewer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sensetile/resources/tango/movie-viewer.png"))); // NOI18N
        mnuMovieViewer.setText(bundle.getString("VIDEO_RECORDER")); // NOI18N
        mnuMovieViewer.setName("mnuMovieViewer"); // NOI18N

        mnuItemStart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnuItemStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sensetile/resources/tango/control_play_blue.png"))); // NOI18N
        mnuItemStart.setText(bundle.getString("START")); // NOI18N
        mnuItemStart.setName("mnuItemStart"); // NOI18N
        mnuItemStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemStartActionPerformed(evt);
            }
        });
        mnuMovieViewer.add(mnuItemStart);

        mnuItemStop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnuItemStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sensetile/resources/tango/control_stop_blue.png"))); // NOI18N
        mnuItemStop.setText(bundle.getString("STOP")); // NOI18N
        mnuItemStop.setName("mnuItemStop"); // NOI18N
        mnuItemStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemStopActionPerformed(evt);
            }
        });
        mnuMovieViewer.add(mnuItemStop);

        mnuOutput.add(mnuMovieViewer);

        mnuBroadcast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sensetile/resources/tango/transmit.png"))); // NOI18N
        mnuBroadcast.setText(bundle.getString("BROADCAST")); // NOI18N
        mnuBroadcast.setName("mnuBroadcast"); // NOI18N

        mnuBroadcastStart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuBroadcastStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sensetile/resources/tango/transmit_add.png"))); // NOI18N
        mnuBroadcastStart.setText(bundle.getString("START")); // NOI18N
        mnuBroadcastStart.setName("mnuBroadcastStart"); // NOI18N
        mnuBroadcast.add(mnuBroadcastStart);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sensetile/resources/tango/transmit_delete.png"))); // NOI18N
        jMenuItem2.setText(bundle.getString("STOP")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        mnuBroadcast.add(jMenuItem2);

        mnuOutput.add(mnuBroadcast);

        jMenuBar1.add(mnuOutput);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panViewerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panViewerMousePressed
    }//GEN-LAST:event_panViewerMousePressed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed



        FrameViewerControler.getInstance().formInternalFrameClosed(_source);
    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
        _source.setSelected(true);
    }//GEN-LAST:event_formInternalFrameDeiconified

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
        _source.setSelected(false);
    }//GEN-LAST:event_formInternalFrameIconified

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if (_source != null) {
            int w = getWidth() * _width / _parentWidth;
            int h = (getHeight() + 6) * _height / (_parentHeight - SenseTileView.DesktopTaskbarHeight);
            _source.setWidth(IVideoSource.DEFAULT_WIDTH);
            _source.setHeight(IVideoSource.DEFAULT_HEIGHT);
        }
    }//GEN-LAST:event_formComponentResized

    private void mnuItemStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemStartActionPerformed
//        avi = new VideoExporterAVI(new File("/home/dragan/JAD/test.avi"));
//        avi.setVideoSource(_source);
//        avi.startExport();
        FrameViewerControler controler = FrameViewerControler.getInstance();
        controler.openFileChooser(_source);
    }//GEN-LAST:event_mnuItemStartActionPerformed

    private void mnuItemStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemStopActionPerformed
         FrameViewerControler controler = FrameViewerControler.getInstance();
        controler.stopExporting(_source);
    }//GEN-LAST:event_mnuItemStopActionPerformed

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (_source != IVideoSource.NO_VIDEO_SOURCE)
        {
            setTitle(FrameViewerControler.getInstance().getTitle(_source));
        }
        
    }

    public JLabel getLblActualFileSize()
    {
        return lblActualFileSize;
    }
    public JLabel getLblActualRecordingTime()
    {
        return lblActualRecordingTime;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grpCaptureSize;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblActualFileSize;
    private javax.swing.JLabel lblActualRecordingTime;
    private javax.swing.JMenu mnuBroadcast;
    private javax.swing.JMenuItem mnuBroadcastStart;
    private javax.swing.JMenuItem mnuItemStart;
    private javax.swing.JMenuItem mnuItemStop;
    private javax.swing.JMenu mnuMovieViewer;
    private javax.swing.JMenu mnuOutput;
    private javax.swing.JPanel panViewer;
    private java.awt.Panel panelStatus;
    // End of variables declaration//GEN-END:variables

}
