//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.01 at 05:02:44 PM GMT 
//


package net.opengis.swe._1_0;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/swe/1.0.1}AbstractEncodingType">
 *       &lt;sequence>
 *         &lt;element name="member" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Component">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *                           &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                           &lt;attribute name="significantBits" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                           &lt;attribute name="bitLength" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                           &lt;attribute name="paddingBits-before" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
 *                           &lt;attribute name="paddingBits-after" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
 *                           &lt;attribute name="encryption" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Block">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *                           &lt;attribute name="byteLength" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                           &lt;attribute name="paddingBytes-before" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
 *                           &lt;attribute name="paddingBytes-after" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
 *                           &lt;attribute name="encryption" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                           &lt;attribute name="compression" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="byteLength" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="byteEncoding" use="required" type="{http://www.opengis.net/swe/1.0.1}byteEncoding" />
 *       &lt;attribute name="byteOrder" use="required" type="{http://www.opengis.net/swe/1.0.1}byteOrder" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "member"
})
@XmlRootElement(name = "BinaryBlock")
public class BinaryBlock
    extends AbstractEncodingType
{

    @XmlElement(required = true)
    protected List<BinaryBlock.Member> member;
    @XmlAttribute
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger byteLength;
    @XmlAttribute(required = true)
    protected ByteEncoding byteEncoding;
    @XmlAttribute(required = true)
    protected ByteOrder byteOrder;

    /**
     * Gets the value of the member property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the member property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMember().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BinaryBlock.Member }
     * 
     * 
     */
    public List<BinaryBlock.Member> getMember() {
        if (member == null) {
            member = new ArrayList<BinaryBlock.Member>();
        }
        return this.member;
    }

    public boolean isSetMember() {
        return ((this.member!= null)&&(!this.member.isEmpty()));
    }

    public void unsetMember() {
        this.member = null;
    }

    /**
     * Gets the value of the byteLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getByteLength() {
        return byteLength;
    }

    /**
     * Sets the value of the byteLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setByteLength(BigInteger value) {
        this.byteLength = value;
    }

    public boolean isSetByteLength() {
        return (this.byteLength!= null);
    }

    /**
     * Gets the value of the byteEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link ByteEncoding }
     *     
     */
    public ByteEncoding getByteEncoding() {
        return byteEncoding;
    }

    /**
     * Sets the value of the byteEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ByteEncoding }
     *     
     */
    public void setByteEncoding(ByteEncoding value) {
        this.byteEncoding = value;
    }

    public boolean isSetByteEncoding() {
        return (this.byteEncoding!= null);
    }

    /**
     * Gets the value of the byteOrder property.
     * 
     * @return
     *     possible object is
     *     {@link ByteOrder }
     *     
     */
    public ByteOrder getByteOrder() {
        return byteOrder;
    }

    /**
     * Sets the value of the byteOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link ByteOrder }
     *     
     */
    public void setByteOrder(ByteOrder value) {
        this.byteOrder = value;
    }

    public boolean isSetByteOrder() {
        return (this.byteOrder!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Component">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
     *                 &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="significantBits" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                 &lt;attribute name="bitLength" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                 &lt;attribute name="paddingBits-before" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
     *                 &lt;attribute name="paddingBits-after" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
     *                 &lt;attribute name="encryption" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Block">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
     *                 &lt;attribute name="byteLength" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                 &lt;attribute name="paddingBytes-before" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
     *                 &lt;attribute name="paddingBytes-after" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
     *                 &lt;attribute name="encryption" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="compression" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "component",
        "block"
    })
    public static class Member {

        @XmlElement(name = "Component")
        protected BinaryBlock.Member.Component component;
        @XmlElement(name = "Block")
        protected BinaryBlock.Member.Block block;

        /**
         * Gets the value of the component property.
         * 
         * @return
         *     possible object is
         *     {@link BinaryBlock.Member.Component }
         *     
         */
        public BinaryBlock.Member.Component getComponent() {
            return component;
        }

        /**
         * Sets the value of the component property.
         * 
         * @param value
         *     allowed object is
         *     {@link BinaryBlock.Member.Component }
         *     
         */
        public void setComponent(BinaryBlock.Member.Component value) {
            this.component = value;
        }

        public boolean isSetComponent() {
            return (this.component!= null);
        }

        /**
         * Gets the value of the block property.
         * 
         * @return
         *     possible object is
         *     {@link BinaryBlock.Member.Block }
         *     
         */
        public BinaryBlock.Member.Block getBlock() {
            return block;
        }

        /**
         * Sets the value of the block property.
         * 
         * @param value
         *     allowed object is
         *     {@link BinaryBlock.Member.Block }
         *     
         */
        public void setBlock(BinaryBlock.Member.Block value) {
            this.block = value;
        }

        public boolean isSetBlock() {
            return (this.block!= null);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
         *       &lt;attribute name="byteLength" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *       &lt;attribute name="paddingBytes-before" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
         *       &lt;attribute name="paddingBytes-after" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
         *       &lt;attribute name="encryption" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="compression" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Block {

            @XmlAttribute(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String ref;
            @XmlAttribute
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger byteLength;
            @XmlAttribute(name = "paddingBytes-before")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger paddingBytesBefore;
            @XmlAttribute(name = "paddingBytes-after")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger paddingBytesAfter;
            @XmlAttribute
            @XmlSchemaType(name = "anyURI")
            protected String encryption;
            @XmlAttribute
            @XmlSchemaType(name = "anyURI")
            protected String compression;

            /**
             * Gets the value of the ref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRef(String value) {
                this.ref = value;
            }

            public boolean isSetRef() {
                return (this.ref!= null);
            }

            /**
             * Gets the value of the byteLength property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getByteLength() {
                return byteLength;
            }

            /**
             * Sets the value of the byteLength property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setByteLength(BigInteger value) {
                this.byteLength = value;
            }

            public boolean isSetByteLength() {
                return (this.byteLength!= null);
            }

            /**
             * Gets the value of the paddingBytesBefore property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPaddingBytesBefore() {
                if (paddingBytesBefore == null) {
                    return new BigInteger("0");
                } else {
                    return paddingBytesBefore;
                }
            }

            /**
             * Sets the value of the paddingBytesBefore property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPaddingBytesBefore(BigInteger value) {
                this.paddingBytesBefore = value;
            }

            public boolean isSetPaddingBytesBefore() {
                return (this.paddingBytesBefore!= null);
            }

            /**
             * Gets the value of the paddingBytesAfter property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPaddingBytesAfter() {
                if (paddingBytesAfter == null) {
                    return new BigInteger("0");
                } else {
                    return paddingBytesAfter;
                }
            }

            /**
             * Sets the value of the paddingBytesAfter property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPaddingBytesAfter(BigInteger value) {
                this.paddingBytesAfter = value;
            }

            public boolean isSetPaddingBytesAfter() {
                return (this.paddingBytesAfter!= null);
            }

            /**
             * Gets the value of the encryption property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEncryption() {
                return encryption;
            }

            /**
             * Sets the value of the encryption property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEncryption(String value) {
                this.encryption = value;
            }

            public boolean isSetEncryption() {
                return (this.encryption!= null);
            }

            /**
             * Gets the value of the compression property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCompression() {
                return compression;
            }

            /**
             * Sets the value of the compression property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCompression(String value) {
                this.compression = value;
            }

            public boolean isSetCompression() {
                return (this.compression!= null);
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
         *       &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="significantBits" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *       &lt;attribute name="bitLength" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *       &lt;attribute name="paddingBits-before" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
         *       &lt;attribute name="paddingBits-after" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
         *       &lt;attribute name="encryption" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Component {

            @XmlAttribute(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String ref;
            @XmlAttribute
            @XmlSchemaType(name = "anyURI")
            protected String dataType;
            @XmlAttribute
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger significantBits;
            @XmlAttribute
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger bitLength;
            @XmlAttribute(name = "paddingBits-before")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger paddingBitsBefore;
            @XmlAttribute(name = "paddingBits-after")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger paddingBitsAfter;
            @XmlAttribute
            @XmlSchemaType(name = "anyURI")
            protected String encryption;

            /**
             * Gets the value of the ref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRef(String value) {
                this.ref = value;
            }

            public boolean isSetRef() {
                return (this.ref!= null);
            }

            /**
             * Gets the value of the dataType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDataType() {
                return dataType;
            }

            /**
             * Sets the value of the dataType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDataType(String value) {
                this.dataType = value;
            }

            public boolean isSetDataType() {
                return (this.dataType!= null);
            }

            /**
             * Gets the value of the significantBits property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSignificantBits() {
                return significantBits;
            }

            /**
             * Sets the value of the significantBits property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSignificantBits(BigInteger value) {
                this.significantBits = value;
            }

            public boolean isSetSignificantBits() {
                return (this.significantBits!= null);
            }

            /**
             * Gets the value of the bitLength property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getBitLength() {
                return bitLength;
            }

            /**
             * Sets the value of the bitLength property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setBitLength(BigInteger value) {
                this.bitLength = value;
            }

            public boolean isSetBitLength() {
                return (this.bitLength!= null);
            }

            /**
             * Gets the value of the paddingBitsBefore property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPaddingBitsBefore() {
                if (paddingBitsBefore == null) {
                    return new BigInteger("0");
                } else {
                    return paddingBitsBefore;
                }
            }

            /**
             * Sets the value of the paddingBitsBefore property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPaddingBitsBefore(BigInteger value) {
                this.paddingBitsBefore = value;
            }

            public boolean isSetPaddingBitsBefore() {
                return (this.paddingBitsBefore!= null);
            }

            /**
             * Gets the value of the paddingBitsAfter property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getPaddingBitsAfter() {
                if (paddingBitsAfter == null) {
                    return new BigInteger("0");
                } else {
                    return paddingBitsAfter;
                }
            }

            /**
             * Sets the value of the paddingBitsAfter property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setPaddingBitsAfter(BigInteger value) {
                this.paddingBitsAfter = value;
            }

            public boolean isSetPaddingBitsAfter() {
                return (this.paddingBitsAfter!= null);
            }

            /**
             * Gets the value of the encryption property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEncryption() {
                return encryption;
            }

            /**
             * Sets the value of the encryption property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEncryption(String value) {
                this.encryption = value;
            }

            public boolean isSetEncryption() {
                return (this.encryption!= null);
            }

        }

    }

}
