//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.01 at 05:02:44 PM GMT 
//


package net.opengis.swe._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A Phenomenon defined as a set of explicitly enumerated components which may or may not be related to one another
 * 
 * <p>Java class for CompositePhenomenonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompositePhenomenonType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/swe/1.0.1}CompoundPhenomenonType">
 *       &lt;sequence>
 *         &lt;element name="base" type="{http://www.opengis.net/swe/1.0.1}PhenomenonPropertyType" minOccurs="0"/>
 *         &lt;element name="component" type="{http://www.opengis.net/swe/1.0.1}PhenomenonPropertyType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompositePhenomenonType", propOrder = {
    "base",
    "component"
})
public class CompositePhenomenonType
    extends CompoundPhenomenonType
{

    protected PhenomenonPropertyType base;
    @XmlElement(required = true)
    protected List<PhenomenonPropertyType> component;

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link PhenomenonPropertyType }
     *     
     */
    public PhenomenonPropertyType getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhenomenonPropertyType }
     *     
     */
    public void setBase(PhenomenonPropertyType value) {
        this.base = value;
    }

    public boolean isSetBase() {
        return (this.base!= null);
    }

    /**
     * Gets the value of the component property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the component property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhenomenonPropertyType }
     * 
     * 
     */
    public List<PhenomenonPropertyType> getComponent() {
        if (component == null) {
            component = new ArrayList<PhenomenonPropertyType>();
        }
        return this.component;
    }

    public boolean isSetComponent() {
        return ((this.component!= null)&&(!this.component.isEmpty()));
    }

    public void unsetComponent() {
        this.component = null;
    }

}
