//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.01 at 05:02:44 PM GMT 
//


package net.opengis.swe._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * CountRange is a data-type so usually appears "by value" rather than by reference.
 * 
 * <p>Java class for CountRangePropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CountRangePropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/swe/1.0.1}CountRange"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CountRangePropertyType", propOrder = {
    "countRange"
})
public class CountRangePropertyType {

    @XmlElement(name = "CountRange", required = true)
    protected CountRange countRange;

    /**
     * Gets the value of the countRange property.
     * 
     * @return
     *     possible object is
     *     {@link CountRange }
     *     
     */
    public CountRange getCountRange() {
        return countRange;
    }

    /**
     * Sets the value of the countRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountRange }
     *     
     */
    public void setCountRange(CountRange value) {
        this.countRange = value;
    }

    public boolean isSetCountRange() {
        return (this.countRange!= null);
    }

}
