//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.01 at 05:02:44 PM GMT 
//


package net.opengis.swe._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * SimpleDataRecord is a data-type so usually appears "by value" rather than by reference.
 * 
 * <p>Java class for SimpleDataRecordPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleDataRecordPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/swe/1.0.1}SimpleDataRecord"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleDataRecordPropertyType", propOrder = {
    "simpleDataRecord"
})
public class SimpleDataRecordPropertyType {

    @XmlElement(name = "SimpleDataRecord", required = true)
    protected SimpleDataRecordType simpleDataRecord;

    /**
     * Gets the value of the simpleDataRecord property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleDataRecordType }
     *     
     */
    public SimpleDataRecordType getSimpleDataRecord() {
        return simpleDataRecord;
    }

    /**
     * Sets the value of the simpleDataRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleDataRecordType }
     *     
     */
    public void setSimpleDataRecord(SimpleDataRecordType value) {
        this.simpleDataRecord = value;
    }

    public boolean isSetSimpleDataRecord() {
        return (this.simpleDataRecord!= null);
    }

}
