//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.01 at 05:02:44 PM GMT 
//


package net.opengis.swe._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/swe/1.0.1}AbstractEncodingType">
 *       &lt;attribute name="tokenSeparator" use="required" type="{http://www.opengis.net/swe/1.0.1}textSeparator" />
 *       &lt;attribute name="blockSeparator" use="required" type="{http://www.opengis.net/swe/1.0.1}textSeparator" />
 *       &lt;attribute name="decimalSeparator" use="required" type="{http://www.opengis.net/swe/1.0.1}decimalSeparator" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "TextBlock")
public class TextBlock
    extends AbstractEncodingType
{

    @XmlAttribute(required = true)
    protected String tokenSeparator;
    @XmlAttribute(required = true)
    protected String blockSeparator;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String decimalSeparator;

    /**
     * Gets the value of the tokenSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenSeparator() {
        return tokenSeparator;
    }

    /**
     * Sets the value of the tokenSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenSeparator(String value) {
        this.tokenSeparator = value;
    }

    public boolean isSetTokenSeparator() {
        return (this.tokenSeparator!= null);
    }

    /**
     * Gets the value of the blockSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockSeparator() {
        return blockSeparator;
    }

    /**
     * Sets the value of the blockSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockSeparator(String value) {
        this.blockSeparator = value;
    }

    public boolean isSetBlockSeparator() {
        return (this.blockSeparator!= null);
    }

    /**
     * Gets the value of the decimalSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalSeparator() {
        return decimalSeparator;
    }

    /**
     * Sets the value of the decimalSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalSeparator(String value) {
        this.decimalSeparator = value;
    }

    public boolean isSetDecimalSeparator() {
        return (this.decimalSeparator!= null);
    }

}
