//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.01 at 05:02:44 PM GMT 
//


package net.opengis.swe._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import net.opengis.gml.v_3_1_1.TimeIntervalLengthType;


/**
 * Extend time instant grid with window size property
 * 
 * <p>Java class for TimeIntervalGridType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeIntervalGridType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/swe/1.0.1}TimeGridType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="windowDuration" type="{http://www.w3.org/2001/XMLSchema}duration"/>
 *           &lt;element name="windowInterval" type="{http://www.opengis.net/gml}TimeIntervalLengthType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeIntervalGridType", propOrder = {
    "windowDuration",
    "windowInterval"
})
public class TimeIntervalGridType
    extends TimeGridType
{

    protected Duration windowDuration;
    protected TimeIntervalLengthType windowInterval;

    /**
     * Gets the value of the windowDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getWindowDuration() {
        return windowDuration;
    }

    /**
     * Sets the value of the windowDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setWindowDuration(Duration value) {
        this.windowDuration = value;
    }

    public boolean isSetWindowDuration() {
        return (this.windowDuration!= null);
    }

    /**
     * Gets the value of the windowInterval property.
     * 
     * @return
     *     possible object is
     *     {@link TimeIntervalLengthType }
     *     
     */
    public TimeIntervalLengthType getWindowInterval() {
        return windowInterval;
    }

    /**
     * Sets the value of the windowInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeIntervalLengthType }
     *     
     */
    public void setWindowInterval(TimeIntervalLengthType value) {
        this.windowInterval = value;
    }

    public boolean isSetWindowInterval() {
        return (this.windowInterval!= null);
    }

}
