//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.01 at 05:02:44 PM GMT 
//


package net.opengis.sensorml._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractDerivableProcessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractDerivableProcessType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/sensorML/1.0.1}AbstractProcessType">
 *       &lt;sequence>
 *         &lt;element name="inputs" type="{http://www.opengis.net/sensorML/1.0.1}inputsPropertyType" minOccurs="0"/>
 *         &lt;element name="outputs" type="{http://www.opengis.net/sensorML/1.0.1}outputsPropertyType" minOccurs="0"/>
 *         &lt;element name="parameters" type="{http://www.opengis.net/sensorML/1.0.1}parametersPropertyType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.opengis.net/sensorML/1.0.1}method"/>
 *           &lt;sequence>
 *             &lt;element name="components" type="{http://www.opengis.net/sensorML/1.0.1}componentsPropertyType"/>
 *             &lt;element name="dataSources" type="{http://www.opengis.net/sensorML/1.0.1}dataSourcesPropertyType" minOccurs="0"/>
 *             &lt;element name="connections" type="{http://www.opengis.net/sensorML/1.0.1}connectionsPropertyType"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractDerivableProcessType", propOrder = {
    "inputs",
    "outputs",
    "parameters",
    "method",
    "components",
    "dataSources",
    "connections"
})
public abstract class AbstractDerivableProcessType
    extends AbstractProcessType
{

    //protected InputsPropertyType inputs;
    protected Inputs inputs;

    //protected OutputsPropertyType outputs;
    protected Outputs outputs;
    protected ParametersPropertyType parameters;
    protected MethodPropertyType method;
    protected ComponentsPropertyType components;
    protected DataSourcesPropertyType dataSources;
    protected ConnectionsPropertyType connections;

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link InputsPropertyType }
     *     
     */
    public Inputs getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputsPropertyType }
     *     
     */
    public void setInputs(Inputs value) {
        this.inputs = value;
    }

    public boolean isSetInputs() {
        return (this.inputs!= null);
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link OutputsPropertyType }
     *     
     */
    public Outputs getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputsPropertyType }
     *     
     */
    public void setOutputs(Outputs value) {
        this.outputs = value;
    }

    public boolean isSetOutputs() {
        return (this.outputs!= null);
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersPropertyType }
     *     
     */
    public ParametersPropertyType getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersPropertyType }
     *     
     */
    public void setParameters(ParametersPropertyType value) {
        this.parameters = value;
    }

    public boolean isSetParameters() {
        return (this.parameters!= null);
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link MethodPropertyType }
     *     
     */
    public MethodPropertyType getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodPropertyType }
     *     
     */
    public void setMethod(MethodPropertyType value) {
        this.method = value;
    }

    public boolean isSetMethod() {
        return (this.method!= null);
    }

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentsPropertyType }
     *     
     */
    public ComponentsPropertyType getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentsPropertyType }
     *     
     */
    public void setComponents(ComponentsPropertyType value) {
        this.components = value;
    }

    public boolean isSetComponents() {
        return (this.components!= null);
    }

    /**
     * Gets the value of the dataSources property.
     * 
     * @return
     *     possible object is
     *     {@link DataSourcesPropertyType }
     *     
     */
    public DataSourcesPropertyType getDataSources() {
        return dataSources;
    }

    /**
     * Sets the value of the dataSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSourcesPropertyType }
     *     
     */
    public void setDataSources(DataSourcesPropertyType value) {
        this.dataSources = value;
    }

    public boolean isSetDataSources() {
        return (this.dataSources!= null);
    }

    /**
     * Gets the value of the connections property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionsPropertyType }
     *     
     */
    public ConnectionsPropertyType getConnections() {
        return connections;
    }

    /**
     * Sets the value of the connections property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionsPropertyType }
     *     
     */
    public void setConnections(ConnectionsPropertyType value) {
        this.connections = value;
    }

    public boolean isSetConnections() {
        return (this.connections!= null);
    }

}
