//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.01 at 05:02:44 PM GMT 
//


package net.opengis.sos._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ObservationOfferingList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ObservationOffering" type="{http://www.opengis.net/sos/1.0}ObservationOfferingType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "observationOfferingList"
})
@XmlRootElement(name = "Contents")
public class Contents {

    @XmlElement(name = "ObservationOfferingList", required = true)
    protected Contents.ObservationOfferingList observationOfferingList;

    /**
     * Gets the value of the observationOfferingList property.
     * 
     * @return
     *     possible object is
     *     {@link Contents.ObservationOfferingList }
     *     
     */
    public Contents.ObservationOfferingList getObservationOfferingList() {
        return observationOfferingList;
    }

    /**
     * Sets the value of the observationOfferingList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contents.ObservationOfferingList }
     *     
     */
    public void setObservationOfferingList(Contents.ObservationOfferingList value) {
        this.observationOfferingList = value;
    }

    public boolean isSetObservationOfferingList() {
        return (this.observationOfferingList!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ObservationOffering" type="{http://www.opengis.net/sos/1.0}ObservationOfferingType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "observationOffering"
    })
    public static class ObservationOfferingList {

        @XmlElement(name = "ObservationOffering", required = true)
        protected List<ObservationOfferingType> observationOffering;

        /**
         * Gets the value of the observationOffering property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the observationOffering property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObservationOffering().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObservationOfferingType }
         * 
         * 
         */
        public List<ObservationOfferingType> getObservationOffering() {
            if (observationOffering == null) {
                observationOffering = new ArrayList<ObservationOfferingType>();
            }
            return this.observationOffering;
        }

        public boolean isSetObservationOffering() {
            return ((this.observationOffering!= null)&&(!this.observationOffering.isEmpty()));
        }

        public void unsetObservationOffering() {
            this.observationOffering = null;
        }

    }

}
