//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.01 at 05:02:44 PM GMT 
//


package net.opengis.sos._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import net.opengis.ogc.BBOXType;
import net.opengis.ogc.BinaryComparisonOpType;
import net.opengis.ogc.BinarySpatialOpType;
import net.opengis.ogc.BinaryTemporalOpType;
import net.opengis.ogc.ComparisonOpsType;
import net.opengis.ogc.DistanceBufferType;
import net.opengis.ogc.PropertyIsBetweenType;
import net.opengis.ogc.PropertyIsLikeType;
import net.opengis.ogc.PropertyIsNullType;
import net.opengis.ogc.SpatialOpsType;
import net.opengis.ogc.TemporalOpsType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/sos/1.0}RequestBaseType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="offering" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="eventTime" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.opengis.net/ogc}temporalOps"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="procedure" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="observedProperty" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded"/>
 *         &lt;element name="featureOfInterest" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.opengis.net/ogc}spatialOps"/>
 *                   &lt;element name="ObjectID" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="result" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.opengis.net/ogc}comparisonOps"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="responseFormat" type="{http://www.opengis.net/ows/1.1}MimeType"/>
 *         &lt;element name="resultModel" type="{http://www.w3.org/2001/XMLSchema}QName" minOccurs="0"/>
 *         &lt;element name="responseMode" type="{http://www.opengis.net/sos/1.0}responseModeType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="srsName" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "offering",
    "eventTime",
    "procedure",
    "observedProperty",
    "featureOfInterest",
    "result",
    "responseFormat",
    "resultModel",
    "responseMode"
})
@XmlRootElement(name = "GetObservation")
public class GetObservation
    extends RequestBaseType
{

    @XmlSchemaType(name = "anyURI")
    protected String offering;
    protected List<GetObservation.EventTime> eventTime;
    @XmlSchemaType(name = "anyURI")
    protected List<String> procedure;
    @XmlSchemaType(name = "anyURI")
    protected List<String> observedProperty;
    protected GetObservation.FeatureOfInterest featureOfInterest;
    protected GetObservation.Result result;
    protected String responseFormat;
    protected QName resultModel;
    protected ResponseModeType responseMode;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String srsName;

    /**
     * Gets the value of the offering property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffering() {
        return offering;
    }

    /**
     * Sets the value of the offering property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffering(String value) {
        this.offering = value;
    }

    public boolean isSetOffering() {
        return (this.offering!= null);
    }

    /**
     * Gets the value of the eventTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetObservation.EventTime }
     * 
     * 
     */
    public List<GetObservation.EventTime> getEventTime() {
        if (eventTime == null) {
            eventTime = new ArrayList<GetObservation.EventTime>();
        }
        return this.eventTime;
    }

    public boolean isSetEventTime() {
        return ((this.eventTime!= null)&&(!this.eventTime.isEmpty()));
    }

    public void unsetEventTime() {
        this.eventTime = null;
    }

    /**
     * Gets the value of the procedure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the procedure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcedure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProcedure() {
        if (procedure == null) {
            procedure = new ArrayList<String>();
        }
        return this.procedure;
    }

    public boolean isSetProcedure() {
        return ((this.procedure!= null)&&(!this.procedure.isEmpty()));
    }

    public void unsetProcedure() {
        this.procedure = null;
    }

    /**
     * Gets the value of the observedProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the observedProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObservedProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getObservedProperty() {
        if (observedProperty == null) {
            observedProperty = new ArrayList<String>();
        }
        return this.observedProperty;
    }

    public boolean isSetObservedProperty() {
        return ((this.observedProperty!= null)&&(!this.observedProperty.isEmpty()));
    }

    public void unsetObservedProperty() {
        this.observedProperty = null;
    }

    /**
     * Gets the value of the featureOfInterest property.
     * 
     * @return
     *     possible object is
     *     {@link GetObservation.FeatureOfInterest }
     *     
     */
    public GetObservation.FeatureOfInterest getFeatureOfInterest() {
        return featureOfInterest;
    }

    /**
     * Sets the value of the featureOfInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetObservation.FeatureOfInterest }
     *     
     */
    public void setFeatureOfInterest(GetObservation.FeatureOfInterest value) {
        this.featureOfInterest = value;
    }

    public boolean isSetFeatureOfInterest() {
        return (this.featureOfInterest!= null);
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link GetObservation.Result }
     *     
     */
    public GetObservation.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetObservation.Result }
     *     
     */
    public void setResult(GetObservation.Result value) {
        this.result = value;
    }

    public boolean isSetResult() {
        return (this.result!= null);
    }

    /**
     * Gets the value of the responseFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseFormat() {
        return responseFormat;
    }

    /**
     * Sets the value of the responseFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseFormat(String value) {
        this.responseFormat = value;
    }

    public boolean isSetResponseFormat() {
        return (this.responseFormat!= null);
    }

    /**
     * Gets the value of the resultModel property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getResultModel() {
        return resultModel;
    }

    /**
     * Sets the value of the resultModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setResultModel(QName value) {
        this.resultModel = value;
    }

    public boolean isSetResultModel() {
        return (this.resultModel!= null);
    }

    /**
     * Gets the value of the responseMode property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseModeType }
     *     
     */
    public ResponseModeType getResponseMode() {
        return responseMode;
    }

    /**
     * Sets the value of the responseMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseModeType }
     *     
     */
    public void setResponseMode(ResponseModeType value) {
        this.responseMode = value;
    }

    public boolean isSetResponseMode() {
        return (this.responseMode!= null);
    }

    /**
     * Gets the value of the srsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrsName() {
        return srsName;
    }

    /**
     * Sets the value of the srsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrsName(String value) {
        this.srsName = value;
    }

    public boolean isSetSrsName() {
        return (this.srsName!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.opengis.net/ogc}temporalOps"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "temporalOps"
    })
    public static class EventTime {

        @XmlElementRef(name = "temporalOps", namespace = "http://www.opengis.net/ogc", type = JAXBElement.class)
        protected JAXBElement<? extends TemporalOpsType> temporalOps;

        /**
         * Gets the value of the temporalOps property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link TemporalOpsType }{@code >}
         *     
         */
        public JAXBElement<? extends TemporalOpsType> getTemporalOps() {
            return temporalOps;
        }

        /**
         * Sets the value of the temporalOps property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryTemporalOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link TemporalOpsType }{@code >}
         *     
         */
        public void setTemporalOps(JAXBElement<? extends TemporalOpsType> value) {
            this.temporalOps = ((JAXBElement<? extends TemporalOpsType> ) value);
        }

        public boolean isSetTemporalOps() {
            return (this.temporalOps!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.opengis.net/ogc}spatialOps"/>
     *         &lt;element name="ObjectID" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "spatialOps",
        "objectID"
    })
    public static class FeatureOfInterest {

        @XmlElementRef(name = "spatialOps", namespace = "http://www.opengis.net/ogc", type = JAXBElement.class)
        protected JAXBElement<? extends SpatialOpsType> spatialOps;
        @XmlElement(name = "ObjectID")
        @XmlSchemaType(name = "anyURI")
        protected List<String> objectID;

        /**
         * Gets the value of the spatialOps property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link DistanceBufferType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link SpatialOpsType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BBOXType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link DistanceBufferType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     
         */
        public JAXBElement<? extends SpatialOpsType> getSpatialOps() {
            return spatialOps;
        }

        /**
         * Sets the value of the spatialOps property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link DistanceBufferType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link SpatialOpsType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BBOXType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link DistanceBufferType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinarySpatialOpType }{@code >}
         *     
         */
        public void setSpatialOps(JAXBElement<? extends SpatialOpsType> value) {
            this.spatialOps = ((JAXBElement<? extends SpatialOpsType> ) value);
        }

        public boolean isSetSpatialOps() {
            return (this.spatialOps!= null);
        }

        /**
         * Gets the value of the objectID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the objectID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObjectID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getObjectID() {
            if (objectID == null) {
                objectID = new ArrayList<String>();
            }
            return this.objectID;
        }

        public boolean isSetObjectID() {
            return ((this.objectID!= null)&&(!this.objectID.isEmpty()));
        }

        public void unsetObjectID() {
            this.objectID = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.opengis.net/ogc}comparisonOps"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "comparisonOps"
    })
    public static class Result {

        @XmlElementRef(name = "comparisonOps", namespace = "http://www.opengis.net/ogc", type = JAXBElement.class)
        protected JAXBElement<? extends ComparisonOpsType> comparisonOps;

        /**
         * Gets the value of the comparisonOps property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link ComparisonOpsType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link PropertyIsNullType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link PropertyIsBetweenType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link PropertyIsLikeType }{@code >}
         *     
         */
        public JAXBElement<? extends ComparisonOpsType> getComparisonOps() {
            return comparisonOps;
        }

        /**
         * Sets the value of the comparisonOps property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link ComparisonOpsType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link PropertyIsNullType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link PropertyIsBetweenType }{@code >}
         *     {@link JAXBElement }{@code <}{@link BinaryComparisonOpType }{@code >}
         *     {@link JAXBElement }{@code <}{@link PropertyIsLikeType }{@code >}
         *     
         */
        public void setComparisonOps(JAXBElement<? extends ComparisonOpsType> value) {
            this.comparisonOps = ((JAXBElement<? extends ComparisonOpsType> ) value);
        }

        public boolean isSetComparisonOps() {
            return (this.comparisonOps!= null);
        }

    }

}
