//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.01 at 05:02:44 PM GMT 
//


package net.opengis.sos._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/sos/1.0}RequestBaseType">
 *       &lt;sequence>
 *         &lt;element name="SensorDescription">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any processContents='lax' namespace='##other'/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.opengis.net/sos/1.0}ObservationTemplate"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sensorDescription",
    "observationTemplate"
})
@XmlRootElement(name = "RegisterSensor")
public class RegisterSensor
    extends RequestBaseType
{

    @XmlElement(name = "SensorDescription", required = true)
    protected RegisterSensor.SensorDescription sensorDescription;
    @XmlElement(name = "ObservationTemplate", required = true)
    protected ObservationTemplate observationTemplate;

    /**
     * Gets the value of the sensorDescription property.
     * 
     * @return
     *     possible object is
     *     {@link RegisterSensor.SensorDescription }
     *     
     */
    public RegisterSensor.SensorDescription getSensorDescription() {
        return sensorDescription;
    }

    /**
     * Sets the value of the sensorDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisterSensor.SensorDescription }
     *     
     */
    public void setSensorDescription(RegisterSensor.SensorDescription value) {
        this.sensorDescription = value;
    }

    public boolean isSetSensorDescription() {
        return (this.sensorDescription!= null);
    }

    /**
     * Gets the value of the observationTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationTemplate }
     *     
     */
    public ObservationTemplate getObservationTemplate() {
        return observationTemplate;
    }

    /**
     * Sets the value of the observationTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationTemplate }
     *     
     */
    public void setObservationTemplate(ObservationTemplate value) {
        this.observationTemplate = value;
    }

    public boolean isSetObservationTemplate() {
        return (this.observationTemplate!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any processContents='lax' namespace='##other'/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class SensorDescription {

        @XmlAnyElement(lax = true)
        protected Object any;

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     {@link Element }
         *     
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     {@link Element }
         *     
         */
        public void setAny(Object value) {
            this.any = value;
        }

        public boolean isSetAny() {
            return (this.any!= null);
        }

    }

}
